### ISSUE TITLE
Bug in template with PVC and ServiceAccount

### ISSUE THREAD

**Issue by DebakelOrakel** [DrPsychick/ark-server-charts#17]
Some csi driver have problems when you define the volume name in the pvc:
https://github.com/DrPsychick/ark-server-charts/blob/master/charts/ark-cluster/templates/pvc.yaml#L66

The service account is missing the namespace:
https://github.com/DrPsychick/ark-server-charts/blob/master/charts/ark-cluster/templates/serviceaccount.yaml

**Comment by DrPsychick** [comment]
Thank you for reporting this, @DebakelOrakel , please feel free to submit a PR if you have a solution at hand for this. I will take a look as soon as I can.

**Comment by DebakelOrakel** [comment]
PR to address the service account issue: #18 

I will look into the other issue theese days 👍

**Comment by DebakelOrakel** [comment]
PR with a quickfix to only include volumeName if using existing pv: #19 

Not sure why you need volumeName otherwise.
