### ISSUE TITLE
Mods not being downloaded (focal)

### ISSUE THREAD

**Issue by Teberon** [DrPsychick/ark-server-charts#2]
As discussed here the issue tracking for the mod downloading that fails

Tue, Apr 13 2021 11:57:54 am | Downloading mod 731604991Executing /home/steam/.steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +workshop_download_item 346110 731604991 +quit
Tue, Apr 13 2021 11:57:54 am | Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
Tue, Apr 13 2021 11:57:54 am | Looks like steam didn't shutdown cleanly, scheduling immediate update check
Tue, Apr 13 2021 11:57:54 am | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Tue, Apr 13 2021 11:57:54 am | [ 0%] Checking for available update...
Tue, Apr 13 2021 11:57:54 am | [----] Downloading update (0 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 0%] Downloading update (3138 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 5%] Downloading update (6648 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 12%] Downloading update (9413 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 17%] Downloading update (11916 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 22%] Downloading update (14424 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 27%] Downloading update (17174 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 32%] Downloading update (19705 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 37%] Downloading update (22188 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 41%] Downloading update (24660 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 46%] Downloading update (27165 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 51%] Downloading update (29630 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 55%] Downloading update (32099 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 60%] Downloading update (34170 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 64%] Downloading update (35422 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 66%] Downloading update (36680 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 68%] Downloading update (38063 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 71%] Downloading update (39318 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 73%] Downloading update (40575 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 76%] Downloading update (41928 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 78%] Downloading update (43154 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 81%] Downloading update (44419 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 83%] Downloading update (45651 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 85%] Downloading update (47025 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 88%] Downloading update (48283 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 90%] Downloading update (49650 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 93%] Downloading update (50881 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 95%] Downloading update (52116 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [ 98%] Downloading update (53165 of 53165 KB)...
Tue, Apr 13 2021 11:57:54 am | [100%] Download Complete.
Tue, Apr 13 2021 11:57:54 am | [----] Applying update...
Tue, Apr 13 2021 11:57:54 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:54 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:54 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:54 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Installing update...
Tue, Apr 13 2021 11:57:54 am | [----] Cleaning up...
Tue, Apr 13 2021 11:57:54 am | [----] Update complete, launching...
Tue, Apr 13 2021 11:57:59 am | Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
Tue, Apr 13 2021 11:57:59 am | [ 0%] Checking for available updates...
Tue, Apr 13 2021 11:57:59 am | [----] Verifying installation...
Tue, Apr 13 2021 11:57:59 am | [ 0%] Downloading update...
Tue, Apr 13 2021 11:57:59 am | [ 0%] Checking for available updates...
Tue, Apr 13 2021 11:57:59 am | [----] Download complete.
Tue, Apr 13 2021 11:57:59 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:59 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:59 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:59 am | [----] Extracting package...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Installing update...
Tue, Apr 13 2021 11:57:59 am | [----] Cleaning up...
Tue, Apr 13 2021 11:57:59 am | [----] Update complete, launching Steamcmd...
Tue, Apr 13 2021 11:58:00 am | Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
Tue, Apr 13 2021 11:58:00 am | [ 0%] Checking for available updates...
Tue, Apr 13 2021 11:58:00 am | [----] Verifying installation...
Tue, Apr 13 2021 11:58:00 am | Steam Console Client (c) Valve Corporation
Tue, Apr 13 2021 11:58:00 am | -- type 'quit' to exit --
Tue, Apr 13 2021 11:58:00 am | Loading Steam API...OK.
Tue, Apr 13 2021 11:58:00 am | "@NoPromptForPassword" = "1"
Tue, Apr 13 2021 11:58:00 am |  
Tue, Apr 13 2021 11:58:01 am | Connecting anonymously to Steam Public...Logged in OK
Tue, Apr 13 2021 11:58:10 am | Waiting for user info...OK
Tue, Apr 13 2021 11:58:10 am | Downloading item 731604991 ...
Tue, Apr 13 2021 11:58:10 am | ERROR! Download item 731604991 failed (I/O Operation Failed).Mod 731604991 was not successfully downloaded

If there's anything else you need, please let me know.

**Comment by Teberon** [comment]
Just figured what you meant with bionic, focal and latest. The issue above happens in latest, bionic does allow to download the mod

--
Tue, Apr 13 2021 12:36:55 pm | Success. Downloaded item 731604991 to "/home/steam/.steam/steamapps/workshop/content/346110/731604991" (59906805 bytes) Mod 731604991 downloaded

**Comment by DrPsychick** [comment]
Labelled "won't fix" as I can't do anything about it, `steamcmd` is not (yet) available on Ubuntu > 18.04 (see https://hub.docker.com/r/steamcmd/steamcmd)

**Comment by DrPsychick** [comment]
New image repo which seems to work for all Ubuntu versions: https://github.com/SickHub/steamcmd
