### ISSUE TITLE
Modifying a sever

### ISSUE THREAD

**Issue by Dracozny** [DrPsychick/ark-server-charts#21]
Perhaps just my ignorance with kubernetes but what would be the best approach to modifying a deployment. for instance if I wanted to add a map?
I tried this:
`helm upgrade --namespace ark --values ~/ark-cluster/values.yaml arkcluster ark/ark-cluster`
 but got a series of  

> spec is immutable after creation except resources.requests for bound claims

My workaround atm is to delete everything in the namespace and then delete the namespace and use the --install string instead.

Separate question, is there a way to make it not try to change the permissions on the folders/files? I have a remote store via fiber channel that is not set to have permissions changed. 
EDIT: I created a new file share that I can change permissions on, but it's still complaining about it not being able to chown. now I'm trying to figure out if that tidbit is a microk8 issue.

**Comment by DrPsychick** [comment]
There are certain specs in k8s objects that cannot be changed. To solve that, delete the object and re-run helm. Assuming you're still trying to get to a final setup.

The adjustment of permissions is required as the user starting the game server is 'steam': https://github.com/SickHub/arkserver/blob/master/run.sh#L14

But it could make sense to add an option to make that optional, i.e. the user must ensure the permissions are right.

**Comment by Dracozny** [comment]
Thanks for the reply.
I will work on the user issue once I get my new (to me) hardware.

I can deal with deleting for now. But on the off chance that ARK releases a
new map how would one go about adding that at a later date?

**Comment by DrPsychick** [comment]
Adding a new map should result in an additional server, so that is easily done by extending the server list. Switching the map on an existing server would result in the same (add new, remove old).

**Comment by Dracozny** [comment]
right it would be an additional server. I guess I'm confused on the command structure. I'll tinker with a few ideas to hopefully understand better.

**Comment by Dracozny** [comment]
> The adjustment of permissions is required as the user starting the game server is 'steam': https://github.com/SickHub/arkserver/blob/master/run.sh#L14

looking at that docker am I mistaken that the docker does not create that user/group? I see that it modifies it and it adds it to the sudo group in the main docker file but the creation of the user I'm not seeing.

**Comment by DrPsychick** [comment]
That's right. As you found, the Dockerfile is based on another Dockerfile while installs steamcmd and can serve as a base for other steam-based containers/games.
https://github.com/SickHub/arkserver/blob/master/Dockerfile#L5

**Comment by DrPsychick** [comment]
Closing this as there is no action to be taken as of now. Feel free to reopen or create a new issue.
