### ISSUE TITLE
Error Calling tpl ... "BasePath" is not a value

### ISSUE THREAD

**Issue by Dracozny** [DrPsychick/ark-server-charts#23]
```
➜  ark-cluster helm upgrade --namespace ark --values values.yaml arkcluster ark/ark-cluster
Error: UPGRADE FAILED: template: ark-cluster/templates/deployment.yaml:241:39: executing "ark-cluster/templates/deployment.yaml" at <tpl $.Values.persistence.game.existingClaim .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: arkcluster-ark-cluster-game: "BasePath" is not a value
```
Doesn't seem to matter what I enter in `existingClaim` it seems to kick out this error. I'm guessing I am missing a value somewhere else but it's not clear to me.

**Comment by DrPsychick** [comment]
The documentation is wrong on this one. The value of `exitingClaim` needs to be a template itself. It is included with the `tel` function of helm:

https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function

`            claimName: {{ printf "%s" (tpl $.Values.persistence.game.existingClaim .) }}`

**Comment by Dracozny** [comment]
I'm not sure I fully grasp the implementation, sorry. 
The few examples there don't entirely jive with the syntax I'm seeing in the deployment.yaml. I guess if I fully understood what the end value is intended to be for 'claimName' I could put it together. 
From what I read it seemed like this is meant to be something along the lines of a file system path, '/ark/' for example.  But I wouldn't think that would make sense for calling out a PVC name.

**Comment by DrPsychick** [comment]
ok, so there is a PV (PersistentVolume) and PVC (PersistentVolumeClaim) in k8s. When you specify `existingClaim` that means you have created a PVC by other means and just point your deployment to use it.

That said, the chart does not support dynamically provisioned PVCs. If I see that correctly, never got around to implement that, sadly. If you are willing to contribute a solution I would be very happy and can support with review and testing.

**Comment by Dracozny** [comment]
Right I understand the claims and PV. thats how I pulled off the trick of connecting to the claim from a replication service pod. But the issue is the syntax for the existingClaim field. You indicated that the field is a  template which is fine, but I don't grasp what exactly I'm entering here. If I copy the syntax I use in the replication pod I get the error indicated in the first post.

Basically what I'm trying to do is keep the existing claims intact. If I remove them, they delete the PV since they are dynamic and the retain policy is delete. (I tried changing it but they for some reason get reverted back. So therefore the workaround I pulled off on the [Ceph permission issue](https://github.com/DrPsychick/ark-server-charts/issues/22#issuecomment-1383553381) would be undone and I would have to start over. Granted I may need to anyways 
 if I change out the drives to ssd, but this way it also ties into https://github.com/DrPsychick/ark-server-charts/issues/21 and I can avoid the Immutable violation when I attempt to run an upgrade from Helm.

**Comment by Dracozny** [comment]
This is what I would expect to enter but as you said this is actually a template so it gives the error.
```
 game:
    existingClaim: arkcluster-ark-cluster-game
```
for reference these are the PVC
```
➜  ark-cluster kubectl get pvc -n ark
NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
...
arkcluster-ark-cluster-fjordur         Bound    pvc-e8460c5e-aad4-42d8-8662-0a2844d6f8c5   2Gi        RWO            ceph-xfs       33h
arkcluster-ark-cluster-game            Bound    pvc-9bd6950f-2941-4143-aa5b-02e78443a47c   30Gi       RWO,RWX        cephfs         33h
...
```
the example from helm docs:
```
# values
template: "{{ .Values.name }}"
name: "Tom"

# template
{{ tpl .Values.template . }}

# output
Tom
```
so I should be able to just use the template `"{{.Values.persistence.game.pvc}}"` and then create a new field under 'game.existingClaim' as `pvc: arkcluster-ark-cluster-game`
However this produces a similar error. 
```
Error: UPGRADE FAILED: template: ark-cluster/templates/deployment.yaml:241:39: executing "ark-cluster/templates/deployment.yaml" at <tpl $.Values.persistence.game.existingClaim .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: {{.Values.persistence.game.pvc}}: "BasePath" is not a value
```
I'm clearly not understanding something. Can you please provide a working example? 
Thank you for taking the time to work with me.

**Comment by DrPsychick** [comment]
found the bug and fixed it. I was completely wrong concerning the templating, or at least, it seems it was never tested.
